# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'CCBluetoothAPISample' do
	use_frameworks!
	pod 'iOSDFULibrary'
    pod 'AFNetworking'
    pod 'SVProgressHUD'
    pod 'Masonry'
    pod 'IQKeyboardManager' 
end
